export const financeModule = {
  layout: 'finance',
  title: 'Manajemen Keuangan',
  description:
    'Rekap pemasukan dan pengeluaran kas, arsip transaksi, dan kontrol aliran dana organisasi dari satu tempat.',
  overviewCards: [
    { label: 'Saldo kas saat ini', value: 'Rp 18,4 jt', note: 'Per 5 April 2026' },
    { label: 'Total pemasukan', value: 'Rp 42,5 jt', note: 'Bulan ini' },
    { label: 'Total pengeluaran', value: 'Rp 24,1 jt', note: 'Bulan ini' },
    { label: 'Transaksi bulan ini', value: '34', note: '8 pending' },
  ],
  categories: ['Semua kategori', 'Dana Masuk', 'Operasional', 'Program Kerja', 'Pengeluaran Lainnya'],
  categoryTypes: {
    'Dana Masuk': 'income',
    'Operasional': 'expense',
    'Program Kerja': 'expense',
    'Pengeluaran Lainnya': 'expense',
  },
  transactionHistory: [
    {
      id: 1,
      date: '2026-04-05',
      description: 'Pemasukan Dana Kas Divisi Humas',
      category: 'Dana Masuk',
      amount: 5000000,
      type: 'income',
      source: 'Divisi Humas',
      status: 'verified',
    },
    {
      id: 2,
      date: '2026-04-04',
      description: 'Pembayaran Snack Gathering IMK',
      category: 'Program Kerja',
      amount: 3500000,
      type: 'expense',
      source: 'Divisi Acara',
      status: 'verified',
    },
    {
      id: 3,
      date: '2026-04-03',
      description: 'Sewa Aula Pengajian Rutin',
      category: 'Program Kerja',
      amount: 1500000,
      type: 'expense',
      source: 'Divisi Rohani',
      status: 'verified',
    },
    {
      id: 4,
      date: '2026-04-02',
      description: 'Pembelian ATK Sekretariat',
      category: 'Operasional',
      amount: 850000,
      type: 'expense',
      source: 'Sekretariat',
      status: 'verified',
    },
    {
      id: 5,
      date: '2026-04-01',
      description: 'Dana Kas dari Iuran Anggota',
      category: 'Dana Masuk',
      amount: 12000000,
      type: 'income',
      source: 'Iuran Bulanan',
      status: 'pending',
    },
  ],
  monthlyTrend: [
    { month: 'Jan', income: 38000000, expense: 22000000 },
    { month: 'Feb', income: 35500000, expense: 19500000 },
    { month: 'Mar', income: 40200000, expense: 25100000 },
    { month: 'Apr', income: 42500000, expense: 24100000 },
  ],
}
