export const workflowsModule = {
  layout: 'workflows',
  title: 'Siklus Program Kerja & Pelaporan',
  description:
    'Kelola alur planned - ongoing - completed, termasuk evaluasi kegiatan, upload dokumentasi, dan input nota pengeluaran.',
  overviewCards: [
    { label: 'Total program kerja', value: '24', note: '3 dalam tahun ini' },
    { label: 'Status ongoing', value: '8', note: '6 terjadwal ' },
    { label: 'Laporan tertunda', value: '3', note: 'Perlu follow-up' },
    { label: 'Program selesai', value: '13', note: 'Dengan laporan' },
  ],
  statusOptions: ['Semua status', 'Planned', 'Ongoing', 'Completed'],
  divisions: ['Humas', 'Rohani', 'PSDM', 'Konsumsi', 'Acara'],
  programList: [
    {
      id: 1,
      name: 'Gathering Keluarga Besar IMK',
      division: 'Humas',
      status: 'Ongoing',
      date: '2026-04-10',
      lead: 'Raka Pratama',
      budget: 'Rp 5.000.000',
      progress: 65,
    },
    {
      id: 2,
      name: 'Pengajian Rutin Bulanan',
      division: 'Rohani',
      status: 'Planned',
      date: '2026-04-15',
      lead: 'Alya Putri',
      budget: 'Rp 2.500.000',
      progress: 20,
    },
    {
      id: 3,
      name: 'Workshop Skill Development',
      division: 'PSDM',
      status: 'Ongoing',
      date: '2026-04-12',
      lead: 'Dimas Nugroho',
      budget: 'Rp 7.500.000',
      progress: 45,
    },
    {
      id: 4,
      name: 'Lomba Cerdas Cermat',
      division: 'Acara',
      status: 'Completed',
      date: '2026-03-28',
      lead: 'Sinta Maharani',
      budget: 'Rp 4.200.000',
      progress: 100,
    },
    {
      id: 5,
      name: 'Donor Darah IMK',
      division: 'Konsumsi',
      status: 'Planned',
      date: '2026-05-01',
      lead: 'Budi Santoso',
      budget: 'Rp 3.000.000',
      progress: 10,
    },
  ],
  statuses: {
    Planned: { color: '#f59e0b', label: 'Akan datang' },
    Ongoing: { color: '#3b82f6', label: 'Sedang berlangsung' },
    Completed: { color: '#10b981', label: 'Selesai' },
  },
}
